DIR_TOP = ..
TARGET = client_parameters
DEFINES = __CLIENT
SRC = \
    parameters_client.cpp

DIRS_INCLUDE = $(DIR_TOP)

CXXFLAGS = -Wno-invalid-offsetof

include $(DIR_TOP)/Makefile.reloaded

all: $(SO)
